/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => AdviseCarePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/gateway.ts
var GatewayClient = class {
  constructor() {
    this.ws = null;
    this.token = "";
    this.gatewayUrl = "";
    this.connected = false;
    this.counter = 0;
    this.pendingRequests = /* @__PURE__ */ new Map();
    this.chatListeners = [];
    this.stateListeners = [];
  }
  onChat(fn) {
    this.chatListeners.push(fn);
  }
  onStateChange(fn) {
    this.stateListeners.push(fn);
  }
  emitChat(payload) {
    for (const fn of this.chatListeners)
      fn(payload);
  }
  emitState(state) {
    this.connected = state;
    for (const fn of this.stateListeners)
      fn(state);
  }
  isConnected() {
    return this.connected;
  }
  nextId() {
    return `advisecare-${++this.counter}-${Date.now()}`;
  }
  toWsUrl(url) {
    return url.replace(/^https:\/\//, "wss://").replace(/^http:\/\//, "ws://").replace(/\/+$/, "");
  }
  connect(gatewayUrl, token) {
    this.disconnect();
    this.gatewayUrl = gatewayUrl;
    this.token = token;
    const wsUrl = this.toWsUrl(gatewayUrl);
    if (!wsUrl) {
      console.error("[AdviseCare] No gateway URL configured");
      return;
    }
    try {
      this.ws = new WebSocket(wsUrl);
    } catch (e) {
      console.error("[AdviseCare] WebSocket init error:", e);
      return;
    }
    this.ws.onopen = () => {
      setTimeout(() => {
        if (this.ws && this.ws.readyState === WebSocket.OPEN && !this.connected) {
          this.sendConnect(null);
        }
      }, 3e3);
    };
    this.ws.onmessage = (evt) => {
      this.handleMessage(evt.data);
    };
    this.ws.onclose = () => {
      this.emitState(false);
    };
    this.ws.onerror = () => {
      this.emitState(false);
    };
  }
  disconnect() {
    if (this.ws) {
      this.ws.onopen = null;
      this.ws.onmessage = null;
      this.ws.onclose = null;
      this.ws.onerror = null;
      if (this.ws.readyState === WebSocket.OPEN || this.ws.readyState === WebSocket.CONNECTING) {
        this.ws.close();
      }
      this.ws = null;
    }
    for (const [, pending] of this.pendingRequests) {
      clearTimeout(pending.timer);
      pending.reject(new Error("Disconnected"));
    }
    this.pendingRequests.clear();
    this.emitState(false);
  }
  handleMessage(data) {
    var _a;
    if (typeof data !== "string")
      return;
    let frame;
    try {
      frame = JSON.parse(data);
    } catch (e) {
      return;
    }
    if (frame.type === "event") {
      if (frame.event === "connect.challenge") {
        const payload = frame.payload;
        this.sendConnect((_a = payload == null ? void 0 : payload.nonce) != null ? _a : null);
      } else if (frame.event === "chat") {
        const payload = frame.payload;
        this.emitChat(payload);
      }
    } else if (frame.type === "res" && frame.id) {
      const pending = this.pendingRequests.get(frame.id);
      if (pending) {
        clearTimeout(pending.timer);
        this.pendingRequests.delete(frame.id);
        pending.resolve(frame);
      }
    }
  }
  sendConnect(nonce) {
    const id = this.nextId();
    const params = {
      minProtocol: 1,
      maxProtocol: 1,
      client: {
        id: "webchat",
        version: "1.0.0",
        platform: "obsidian",
        mode: "ui",
        displayName: "Obsidian"
      },
      role: "operator",
      scopes: ["operator.read", "operator.write"],
      auth: { token: this.token }
    };
    if (nonce)
      params.nonce = nonce;
    const frame = { type: "req", id, method: "connect", params };
    this.sendFrame(frame);
    this.pendingRequests.set(id, {
      resolve: (res) => {
        if (res.ok) {
          this.emitState(true);
        } else {
          console.error("[AdviseCare] Connect rejected:", res.error);
          this.emitState(false);
        }
      },
      reject: (err) => {
        console.error("[AdviseCare] Connect failed:", err);
      },
      timer: setTimeout(() => {
        this.pendingRequests.delete(id);
        console.error("[AdviseCare] Connect timed out");
      }, 1e4)
    });
  }
  async sendChat(sessionKey, message) {
    const id = this.nextId();
    return new Promise((resolve, reject) => {
      const frame = {
        type: "req",
        id,
        method: "chat.send",
        params: {
          sessionKey,
          message,
          idempotencyKey: id
        }
      };
      this.pendingRequests.set(id, {
        resolve: (res) => {
          var _a, _b;
          if (res.ok)
            resolve();
          else
            reject(new Error((_b = (_a = res.error) == null ? void 0 : _a.message) != null ? _b : "chat.send failed"));
        },
        reject,
        timer: setTimeout(() => {
          this.pendingRequests.delete(id);
          reject(new Error("chat.send timed out"));
        }, 15e3)
      });
      this.sendFrame(frame);
    });
  }
  async testConnection(gatewayUrl, token) {
    return new Promise((resolve, reject) => {
      const wsUrl = this.toWsUrl(gatewayUrl);
      let ws;
      try {
        ws = new WebSocket(wsUrl);
      } catch (e) {
        reject(new Error("Invalid URL"));
        return;
      }
      const timer = setTimeout(() => {
        ws.close();
        reject(new Error("Connection timed out"));
      }, 8e3);
      let challengeHandled = false;
      const tryConnect = (nonce) => {
        if (challengeHandled)
          return;
        challengeHandled = true;
        const id = `test-${Date.now()}`;
        const params = {
          minProtocol: 1,
          maxProtocol: 1,
          client: { id: "webchat", version: "1.0.0", platform: "obsidian", mode: "ui", displayName: "Obsidian" },
          role: "operator",
          scopes: ["operator.read", "operator.write"],
          auth: { token }
        };
        if (nonce)
          params.nonce = nonce;
        ws.send(JSON.stringify({ type: "req", id, method: "connect", params }));
        ws.onmessage = (evt) => {
          var _a, _b;
          try {
            const frame = JSON.parse(evt.data);
            if (frame.type === "res" && frame.id === id) {
              clearTimeout(timer);
              ws.close();
              if (frame.ok)
                resolve("Connected successfully");
              else
                reject(new Error((_b = (_a = frame.error) == null ? void 0 : _a.message) != null ? _b : "Auth failed"));
            }
          } catch (e) {
          }
        };
      };
      ws.onopen = () => {
        setTimeout(() => tryConnect(null), 3e3);
      };
      ws.addEventListener("message", (evt) => {
        var _a;
        try {
          const frame = JSON.parse(evt.data);
          if (frame.type === "event" && frame.event === "connect.challenge") {
            const payload = frame.payload;
            tryConnect((_a = payload == null ? void 0 : payload.nonce) != null ? _a : null);
          }
        } catch (e) {
        }
      });
      ws.onerror = () => {
        clearTimeout(timer);
        reject(new Error("Connection failed \u2014 check URL and that gateway is running"));
      };
      ws.onclose = () => {
        clearTimeout(timer);
      };
    });
  }
  sendFrame(frame) {
    if (this.ws && this.ws.readyState === WebSocket.OPEN) {
      this.ws.send(JSON.stringify(frame));
    }
  }
};

// src/chat-view.ts
var import_obsidian = require("obsidian");
var CHAT_VIEW_TYPE = "advisecare-chat";
var ChatView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin, gateway) {
    super(leaf);
    this.messages = [];
    this.messagesEl = null;
    this.inputEl = null;
    this.sendBtn = null;
    this.statusEl = null;
    this.streamBuffer = "";
    this.streamMsgEl = null;
    this.isStreaming = false;
    this.plugin = plugin;
    this.gateway = gateway;
  }
  getViewType() {
    return CHAT_VIEW_TYPE;
  }
  getDisplayText() {
    return `${this.plugin.settings.agentName} \u2014 AdviseCare`;
  }
  getIcon() {
    return "message-circle";
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("advisecare-chat-container");
    const header = container.createDiv({ cls: "advisecare-header" });
    header.createEl("span", {
      cls: "advisecare-header-title",
      text: this.plugin.settings.agentName
    });
    const clearBtn = header.createEl("button", {
      cls: "advisecare-clear-btn",
      text: "Clear"
    });
    clearBtn.addEventListener("click", () => this.clearMessages());
    this.statusEl = container.createDiv({ cls: "advisecare-status-bar" });
    this.updateStatus();
    this.messagesEl = container.createDiv({ cls: "advisecare-messages" });
    for (const msg of this.messages) {
      this.renderMessage(msg);
    }
    this.scrollToBottom();
    if (!this.plugin.runtimeToken) {
      this.showTokenWarning();
    }
    const inputArea = container.createDiv({ cls: "advisecare-input-area" });
    this.inputEl = inputArea.createEl("textarea", {
      cls: "advisecare-input",
      attr: { placeholder: `Message ${this.plugin.settings.agentName}\u2026`, rows: "3" }
    });
    this.inputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        this.handleSend();
      }
    });
    this.sendBtn = inputArea.createEl("button", {
      cls: "advisecare-send-btn",
      text: "Send"
    });
    this.sendBtn.addEventListener("click", () => this.handleSend());
    this.gateway.onChat((payload) => {
      if (payload.error) {
        this.finishStream();
        this.addMessage({ role: "assistant", content: `Error: ${payload.error}`, timestamp: Date.now() });
        this.setInputDisabled(false);
        return;
      }
      if (payload.delta) {
        this.appendStream(payload.delta);
      }
      if (payload.done) {
        this.finishStream();
        this.setInputDisabled(false);
      }
    });
    this.gateway.onStateChange((connected) => {
      this.updateStatus();
      if (!connected && this.isStreaming) {
        this.finishStream();
        this.setInputDisabled(false);
      }
    });
  }
  showTokenWarning() {
    var _a;
    if (!this.messagesEl)
      return;
    const warn = this.messagesEl.createDiv({ cls: "advisecare-token-warning" });
    warn.innerHTML = `\u26A0\uFE0F Gateway token not set. <a class="advisecare-settings-link">Open Settings</a> to enter your token.`;
    (_a = warn.querySelector(".advisecare-settings-link")) == null ? void 0 : _a.addEventListener("click", () => {
      this.app.setting.open();
      this.app.setting.openTabById("advisecare-agent");
    });
  }
  updateStatus() {
    if (!this.statusEl)
      return;
    const connected = this.gateway.isConnected();
    this.statusEl.setText(connected ? "\u25CF Connected" : "\u25CB Disconnected");
    this.statusEl.className = `advisecare-status-bar ${connected ? "connected" : "disconnected"}`;
  }
  renderMessage(msg) {
    if (!this.messagesEl)
      return;
    const el = this.messagesEl.createDiv({
      cls: `advisecare-message advisecare-message-${msg.role}`
    });
    const bubble = el.createDiv({ cls: "advisecare-bubble" });
    bubble.setText(msg.content);
  }
  appendStream(delta) {
    if (!this.messagesEl)
      return;
    if (!this.isStreaming) {
      this.isStreaming = true;
      this.streamBuffer = "";
      const el = this.messagesEl.createDiv({
        cls: "advisecare-message advisecare-message-assistant advisecare-streaming"
      });
      this.streamMsgEl = el.createDiv({ cls: "advisecare-bubble" });
    }
    this.streamBuffer += delta;
    if (this.streamMsgEl) {
      this.streamMsgEl.setText(this.streamBuffer);
    }
    this.scrollToBottom();
  }
  finishStream() {
    var _a, _b;
    if (!this.isStreaming)
      return;
    this.isStreaming = false;
    if (this.streamBuffer) {
      this.messages.push({
        role: "assistant",
        content: this.streamBuffer,
        timestamp: Date.now()
      });
    }
    this.streamBuffer = "";
    this.streamMsgEl = null;
    (_b = (_a = this.messagesEl) == null ? void 0 : _a.querySelector(".advisecare-streaming")) == null ? void 0 : _b.removeClass("advisecare-streaming");
  }
  addMessage(msg) {
    this.messages.push(msg);
    this.renderMessage(msg);
    this.scrollToBottom();
  }
  async handleSend() {
    var _a, _b;
    const text = (_b = (_a = this.inputEl) == null ? void 0 : _a.value) == null ? void 0 : _b.trim();
    if (!text)
      return;
    if (!this.gateway.isConnected()) {
      new import_obsidian.Notice("Not connected to gateway. Check Settings.");
      return;
    }
    if (!this.plugin.runtimeToken) {
      new import_obsidian.Notice("Gateway token not set. Open Settings to enter it.");
      return;
    }
    this.addMessage({ role: "user", content: text, timestamp: Date.now() });
    if (this.inputEl)
      this.inputEl.value = "";
    this.setInputDisabled(true);
    try {
      await this.gateway.sendChat(this.plugin.settings.sessionKey, text);
    } catch (e) {
      this.finishStream();
      this.addMessage({ role: "assistant", content: `Failed to send: ${e.message}`, timestamp: Date.now() });
      this.setInputDisabled(false);
    }
  }
  setInputDisabled(disabled) {
    if (this.inputEl)
      this.inputEl.disabled = disabled;
    if (this.sendBtn)
      this.sendBtn.disabled = disabled;
  }
  clearMessages() {
    this.messages = [];
    if (this.messagesEl) {
      this.messagesEl.empty();
      if (!this.plugin.runtimeToken) {
        this.showTokenWarning();
      }
    }
  }
  scrollToBottom() {
    if (this.messagesEl) {
      this.messagesEl.scrollTop = this.messagesEl.scrollHeight;
    }
  }
  async onClose() {
  }
};

// src/settings.ts
var import_obsidian2 = require("obsidian");
var AdviseCareSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin, gateway) {
    super(app, plugin);
    this.tokenField = null;
    this.plugin = plugin;
    this.gateway = gateway;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "AdviseCare Agent Settings" });
    new import_obsidian2.Setting(containerEl).setName("Gateway URL").setDesc("Your OpenClaw gateway URL. E.g. https://your-machine.your-tailnet.ts.net").addText(
      (text) => text.setPlaceholder("https://your-gateway.ts.net").setValue(this.plugin.settings.gatewayUrl).onChange(async (value) => {
        this.plugin.settings.gatewayUrl = value.replace(/\/+$/, "");
        await this.plugin.saveSettings();
      })
    );
    const tokenSetting = new import_obsidian2.Setting(containerEl).setName("Gateway Token").setDesc(
      "Authentication token. Stored in memory only \u2014 you will need to re-enter after restarting Obsidian."
    );
    tokenSetting.addText((text) => {
      this.tokenField = text.inputEl;
      text.inputEl.type = "password";
      text.inputEl.placeholder = "Paste your gateway token";
      text.inputEl.value = this.plugin.runtimeToken;
      text.inputEl.addEventListener("change", (e) => {
        this.plugin.runtimeToken = e.target.value.trim();
      });
    });
    new import_obsidian2.Setting(containerEl).setName("Agent Name").setDesc("Display name for your AI agent").addText(
      (text) => text.setPlaceholder("Max").setValue(this.plugin.settings.agentName).onChange(async (value) => {
        this.plugin.settings.agentName = value || "Max";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Session Key").setDesc("Gateway session key (advanced \u2014 leave as default unless told otherwise)").addText(
      (text) => text.setPlaceholder("obsidian:main").setValue(this.plugin.settings.sessionKey).onChange(async (value) => {
        this.plugin.settings.sessionKey = value || "obsidian:main";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Test Connection").setDesc("Verify your gateway URL and token are working").addButton(
      (btn) => btn.setButtonText("Test").setCta().onClick(async () => {
        const url = this.plugin.settings.gatewayUrl;
        const token = this.plugin.runtimeToken;
        if (!url) {
          new import_obsidian2.Notice("Enter a Gateway URL first.");
          return;
        }
        if (!token) {
          new import_obsidian2.Notice("Enter a Gateway Token first.");
          return;
        }
        btn.setButtonText("Testing\u2026");
        btn.setDisabled(true);
        try {
          const result = await this.gateway.testConnection(url, token);
          new import_obsidian2.Notice(`\u2705 ${result}`);
          this.plugin.connectGateway();
        } catch (e) {
          new import_obsidian2.Notice(`\u274C ${e.message}`);
        } finally {
          btn.setButtonText("Test");
          btn.setDisabled(false);
        }
      })
    );
    const status = containerEl.createDiv({ cls: "advisecare-status" });
    const connected = this.gateway.isConnected();
    status.setText(connected ? "\u25CF Connected to gateway" : "\u25CB Not connected");
    status.style.color = connected ? "var(--color-green)" : "var(--text-muted)";
    status.style.marginTop = "12px";
    status.style.fontSize = "0.85em";
  }
};

// src/types.ts
var DEFAULT_SETTINGS = {
  gatewayUrl: "",
  agentName: "Max",
  sessionKey: "obsidian:main"
};

// main.ts
var AdviseCarePlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.settings = { ...DEFAULT_SETTINGS };
    this.gateway = new GatewayClient();
    // Token lives in memory only — never persisted to disk
    this.runtimeToken = "";
  }
  async onload() {
    await this.loadSettings();
    this.registerView(CHAT_VIEW_TYPE, (leaf) => new ChatView(leaf, this, this.gateway));
    this.addRibbonIcon("message-circle", "Open AdviseCare Chat", () => {
      this.activateChatView();
    });
    this.addCommand({
      id: "open-advisecare-chat",
      name: "Open AdviseCare Chat",
      callback: () => this.activateChatView()
    });
    this.addSettingTab(new AdviseCareSettingTab(this.app, this, this.gateway));
    if (this.settings.gatewayUrl) {
      setTimeout(() => this.connectGateway(), 1e3);
    }
    console.log("AdviseCare Agent loaded");
  }
  async onunload() {
    this.gateway.disconnect();
    console.log("AdviseCare Agent unloaded");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  connectGateway() {
    if (!this.settings.gatewayUrl || !this.runtimeToken)
      return;
    this.gateway.connect(this.settings.gatewayUrl, this.runtimeToken);
  }
  async activateChatView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(CHAT_VIEW_TYPE);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getRightLeaf(false);
      if (leaf) {
        await leaf.setViewState({ type: CHAT_VIEW_TYPE, active: true });
      }
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
    }
  }
};
