/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => OcChatPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/gateway.ts
var GatewayClient = class {
  constructor() {
    this.ws = null;
    this.token = "";
    this.gatewayUrl = "";
    this.connected = false;
    this.counter = 0;
    this.pendingRequests = /* @__PURE__ */ new Map();
    this.chatListeners = [];
    this.stateListeners = [];
  }
  onChat(fn) {
    this.chatListeners.push(fn);
  }
  onStateChange(fn) {
    this.stateListeners.push(fn);
  }
  offChat(fn) {
    this.chatListeners = this.chatListeners.filter((f) => f !== fn);
  }
  offStateChange(fn) {
    this.stateListeners = this.stateListeners.filter((f) => f !== fn);
  }
  emitChat(payload) {
    for (const fn of this.chatListeners)
      fn(payload);
  }
  emitState(state) {
    this.connected = state;
    for (const fn of this.stateListeners)
      fn(state);
  }
  isConnected() {
    return this.connected;
  }
  nextId() {
    return `oc-${++this.counter}-${Date.now()}`;
  }
  toWsUrl(url) {
    return url.replace(/^https:\/\//, "wss://").replace(/^http:\/\//, "ws://").replace(/\/+$/, "");
  }
  connect(gatewayUrl, token) {
    this.disconnect();
    this.gatewayUrl = gatewayUrl;
    this.token = token;
    const wsUrl = this.toWsUrl(gatewayUrl);
    if (!wsUrl) {
      console.error("[OpenClaw] No gateway URL configured");
      return;
    }
    try {
      this.ws = new WebSocket(wsUrl);
    } catch (e) {
      console.error("[OpenClaw] WebSocket init error:", e);
      return;
    }
    this.ws.onopen = () => {
      setTimeout(() => {
        if (this.ws && this.ws.readyState === WebSocket.OPEN && !this.connected) {
          this.sendConnect(null);
        }
      }, 3e3);
    };
    this.ws.onmessage = (evt) => {
      this.handleMessage(evt.data);
    };
    this.ws.onclose = () => {
      this.emitState(false);
    };
    this.ws.onerror = () => {
      this.emitState(false);
    };
  }
  disconnect() {
    if (this.ws) {
      this.ws.onopen = null;
      this.ws.onmessage = null;
      this.ws.onclose = null;
      this.ws.onerror = null;
      if (this.ws.readyState === WebSocket.OPEN || this.ws.readyState === WebSocket.CONNECTING) {
        this.ws.close();
      }
      this.ws = null;
    }
    for (const [, pending] of this.pendingRequests) {
      clearTimeout(pending.timer);
      pending.reject(new Error("Disconnected"));
    }
    this.pendingRequests.clear();
    this.emitState(false);
  }
  handleMessage(data) {
    var _a;
    if (typeof data !== "string")
      return;
    let frame;
    try {
      frame = JSON.parse(data);
    } catch (e) {
      return;
    }
    if (frame.type === "event") {
      if (frame.event === "connect.challenge") {
        const payload = frame.payload;
        this.sendConnect((_a = payload == null ? void 0 : payload.nonce) != null ? _a : null);
      } else if (frame.event === "chat") {
        const payload = frame.payload;
        this.emitChat(payload);
      }
    } else if (frame.type === "res" && frame.id) {
      const pending = this.pendingRequests.get(frame.id);
      if (pending) {
        clearTimeout(pending.timer);
        this.pendingRequests.delete(frame.id);
        pending.resolve(frame);
      }
    }
  }
  sendConnect(nonce) {
    const id = this.nextId();
    const params = {
      minProtocol: 3,
      maxProtocol: 3,
      client: {
        id: "webchat",
        version: "1.0.0",
        platform: "obsidian",
        mode: "ui",
        displayName: "Obsidian"
      },
      role: "operator",
      scopes: ["operator.read", "operator.write"],
      auth: { token: this.token }
    };
    const frame = { type: "req", id, method: "connect", params };
    this.sendFrame(frame);
    this.pendingRequests.set(id, {
      resolve: (res) => {
        if (res.ok) {
          this.emitState(true);
        } else {
          console.error("[OpenClaw] Connect rejected:", res.error);
          this.emitState(false);
        }
      },
      reject: (err) => {
        console.error("[OpenClaw] Connect failed:", err);
      },
      timer: setTimeout(() => {
        this.pendingRequests.delete(id);
        console.error("[OpenClaw] Connect timed out");
      }, 1e4)
    });
  }
  async sendChat(sessionKey, message) {
    const id = this.nextId();
    return new Promise((resolve, reject) => {
      const frame = {
        type: "req",
        id,
        method: "chat.send",
        params: {
          sessionKey,
          message,
          idempotencyKey: id
        }
      };
      this.pendingRequests.set(id, {
        resolve: (res) => {
          var _a, _b;
          if (res.ok)
            resolve();
          else
            reject(new Error((_b = (_a = res.error) == null ? void 0 : _a.message) != null ? _b : "chat.send failed"));
        },
        reject,
        timer: setTimeout(() => {
          this.pendingRequests.delete(id);
          reject(new Error("chat.send timed out"));
        }, 15e3)
      });
      this.sendFrame(frame);
    });
  }
  async testConnection(gatewayUrl, token) {
    return new Promise((resolve, reject) => {
      const wsUrl = this.toWsUrl(gatewayUrl);
      let ws;
      try {
        ws = new WebSocket(wsUrl);
      } catch (e) {
        reject(new Error("Invalid URL"));
        return;
      }
      const timer = setTimeout(() => {
        ws.close();
        reject(new Error("Connection timed out"));
      }, 8e3);
      let challengeHandled = false;
      const tryConnect = (nonce) => {
        if (challengeHandled)
          return;
        challengeHandled = true;
        const id = `test-${Date.now()}`;
        const params = {
          minProtocol: 3,
          maxProtocol: 3,
          client: { id: "webchat", version: "1.0.0", platform: "obsidian", mode: "ui", displayName: "Obsidian" },
          role: "operator",
          scopes: ["operator.read", "operator.write"],
          auth: { token }
        };
        ws.send(JSON.stringify({ type: "req", id, method: "connect", params }));
        ws.onmessage = (evt) => {
          var _a, _b;
          try {
            const frame = JSON.parse(evt.data);
            if (frame.type === "res" && frame.id === id) {
              clearTimeout(timer);
              ws.close();
              if (frame.ok)
                resolve("Connected successfully");
              else
                reject(new Error((_b = (_a = frame.error) == null ? void 0 : _a.message) != null ? _b : "Auth failed"));
            }
          } catch (e) {
          }
        };
      };
      ws.onopen = () => {
        setTimeout(() => tryConnect(null), 3e3);
      };
      ws.addEventListener("message", (evt) => {
        var _a;
        try {
          const frame = JSON.parse(evt.data);
          if (frame.type === "event" && frame.event === "connect.challenge") {
            const payload = frame.payload;
            tryConnect((_a = payload == null ? void 0 : payload.nonce) != null ? _a : null);
          }
        } catch (e) {
        }
      });
      ws.onerror = () => {
        clearTimeout(timer);
        reject(new Error("Connection failed \u2014 check URL and that gateway is running"));
      };
      ws.onclose = () => {
        clearTimeout(timer);
      };
    });
  }
  sendFrame(frame) {
    if (this.ws && this.ws.readyState === WebSocket.OPEN) {
      this.ws.send(JSON.stringify(frame));
    }
  }
};
var GatewayManager = class {
  constructor() {
    this.clients = /* @__PURE__ */ new Map();
  }
  getClient(agentId) {
    let client = this.clients.get(agentId);
    if (!client) {
      client = new GatewayClient();
      this.clients.set(agentId, client);
    }
    return client;
  }
  connectAgent(agentId, gatewayUrl, token) {
    const client = this.getClient(agentId);
    client.connect(gatewayUrl, token);
  }
  disconnectAgent(agentId) {
    const client = this.clients.get(agentId);
    if (client) {
      client.disconnect();
    }
  }
  disconnectAll() {
    for (const [, client] of this.clients) {
      client.disconnect();
    }
  }
  removeAgent(agentId) {
    this.disconnectAgent(agentId);
    this.clients.delete(agentId);
  }
  isConnected(agentId) {
    var _a, _b;
    return (_b = (_a = this.clients.get(agentId)) == null ? void 0 : _a.isConnected()) != null ? _b : false;
  }
};

// src/chat-view.ts
var import_obsidian = require("obsidian");
var CHAT_VIEW_TYPE = "oc-chat";
var ChatView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.activeAgentId = null;
    // Per-agent chat state (in-memory)
    this.agentStates = /* @__PURE__ */ new Map();
    // Per-agent listener references for cleanup
    this.boundListeners = /* @__PURE__ */ new Map();
    // DOM refs
    this.tabBarEl = null;
    this.chatAreaEl = null;
    this.messagesEl = null;
    this.inputEl = null;
    this.sendBtn = null;
    this.statusEl = null;
    this.emptyStateEl = null;
    this.includeNoteCheckbox = null;
    this.plugin = plugin;
  }
  getViewType() {
    return CHAT_VIEW_TYPE;
  }
  getDisplayText() {
    return "OpenClaw Chat";
  }
  getIcon() {
    return "message-circle";
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("oc-chat-container");
    this.tabBarEl = container.createDiv({ cls: "oc-tab-bar" });
    this.chatAreaEl = container.createDiv({ cls: "oc-chat-area" });
    const statusRow = this.chatAreaEl.createDiv({ cls: "oc-status-row" });
    this.statusEl = statusRow.createSpan({ cls: "oc-status-bar disconnected" });
    this.statusEl.setText("\u25CB Disconnected");
    const clearBtn = statusRow.createEl("button", { cls: "oc-clear-btn", text: "Clear" });
    clearBtn.addEventListener("click", () => this.clearActiveChat());
    this.messagesEl = this.chatAreaEl.createDiv({ cls: "oc-messages" });
    this.emptyStateEl = container.createDiv({ cls: "oc-empty-state" });
    const inputArea = this.chatAreaEl.createDiv({ cls: "oc-input-area" });
    const inputOptions = inputArea.createDiv({ cls: "oc-input-options" });
    const noteLabel = inputOptions.createEl("label", { cls: "oc-include-note-label" });
    this.includeNoteCheckbox = noteLabel.createEl("input", { attr: { type: "checkbox" } });
    noteLabel.createSpan({ text: "Include current note" });
    const inputRow = inputArea.createDiv({ cls: "oc-input-row" });
    this.inputEl = inputRow.createEl("textarea", {
      cls: "oc-input",
      attr: { placeholder: "Message\u2026", rows: "2" }
    });
    this.inputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        this.handleSend();
      }
    });
    this.sendBtn = inputRow.createEl("button", { cls: "oc-send-btn" });
    (0, import_obsidian.setIcon)(this.sendBtn, "send");
    this.sendBtn.setAttribute("aria-label", "Send");
    this.sendBtn.addEventListener("click", () => this.handleSend());
    this.buildTabs();
    this.bindAllAgentListeners();
    const enabled = this.plugin.settings.agents.filter((a) => a.enabled);
    if (enabled.length > 0) {
      this.switchToAgent(enabled[0].id);
    } else {
      this.showEmptyState();
    }
  }
  /** Called by plugin when agent list changes */
  refresh() {
    this.unbindAllAgentListeners();
    this.buildTabs();
    this.bindAllAgentListeners();
    const enabled = this.plugin.settings.agents.filter((a) => a.enabled);
    if (enabled.length === 0) {
      this.activeAgentId = null;
      this.showEmptyState();
    } else if (!this.activeAgentId || !enabled.find((a) => a.id === this.activeAgentId)) {
      this.switchToAgent(enabled[0].id);
    } else {
      this.switchToAgent(this.activeAgentId);
    }
  }
  switchToAgent(agentId) {
    var _a;
    this.activeAgentId = agentId;
    const agent = this.plugin.settings.agents.find((a) => a.id === agentId);
    if (!agent)
      return;
    if (this.emptyStateEl)
      this.emptyStateEl.style.display = "none";
    if (this.chatAreaEl)
      this.chatAreaEl.style.display = "flex";
    (_a = this.tabBarEl) == null ? void 0 : _a.querySelectorAll(".oc-tab").forEach((tab) => {
      tab.toggleClass("active", tab.getAttribute("data-agent-id") === agentId);
    });
    if (this.inputEl) {
      this.inputEl.placeholder = `Message ${agent.name || "Agent"}\u2026`;
    }
    this.renderMessages();
    this.updateStatus();
    const hasToken = this.plugin.tokenStore.has(agentId);
    const connected = this.plugin.gatewayManager.isConnected(agentId);
    if (!hasToken && !connected) {
      this.showInlineWarning("Token not set \u2014 open Settings to enter your gateway token.");
    }
  }
  // ─── Tab bar ───
  buildTabs() {
    if (!this.tabBarEl)
      return;
    this.tabBarEl.empty();
    const enabled = this.plugin.settings.agents.filter((a) => a.enabled);
    for (const agent of enabled) {
      const tab = this.tabBarEl.createDiv({
        cls: "oc-tab",
        attr: { "data-agent-id": agent.id }
      });
      const connected = this.plugin.gatewayManager.isConnected(agent.id);
      tab.createSpan({ cls: `oc-tab-dot ${connected ? "connected" : "disconnected"}` });
      tab.createSpan({ cls: "oc-tab-name", text: agent.name || "Agent" });
      tab.addEventListener("click", () => this.switchToAgent(agent.id));
      if (agent.id === this.activeAgentId) {
        tab.addClass("active");
      }
    }
    const addTab = this.tabBarEl.createDiv({ cls: "oc-tab oc-tab-add" });
    addTab.createSpan({ text: "+" });
    addTab.addEventListener("click", () => {
      this.app.setting.open();
      this.app.setting.openTabById("openclaw-chat");
    });
  }
  // ─── Listener management ───
  bindAllAgentListeners() {
    for (const agent of this.plugin.settings.agents) {
      if (!agent.enabled)
        continue;
      this.bindAgentListeners(agent);
    }
  }
  bindAgentListeners(agent) {
    if (this.boundListeners.has(agent.id))
      return;
    const client = this.plugin.gatewayManager.getClient(agent.id);
    const chatListener = (payload) => {
      this.handleChatEvent(agent.id, payload);
    };
    const stateListener = (connected) => {
      this.handleStateChange(agent.id, connected);
    };
    client.onChat(chatListener);
    client.onStateChange(stateListener);
    this.boundListeners.set(agent.id, { chat: chatListener, state: stateListener });
  }
  unbindAllAgentListeners() {
    for (const [agentId, listeners] of this.boundListeners) {
      const client = this.plugin.gatewayManager.getClient(agentId);
      client.offChat(listeners.chat);
      client.offStateChange(listeners.state);
    }
    this.boundListeners.clear();
  }
  // ─── Event handlers ───
  handleChatEvent(agentId, payload) {
    var _a;
    const state = this.getAgentState(agentId);
    const agent = this.plugin.settings.agents.find((a) => a.id === agentId);
    if (agent) {
      const ourKey = agent.sessionKey || "obsidian:main";
      if (!payload.sessionKey || !payload.sessionKey.includes(ourKey)) {
        return;
      }
    }
    if (payload.state === "final" && payload.message) {
      const text = payload.message.content.filter((c) => c.type === "text").map((c) => c.text).join("").trim();
      if (text === "HEARTBEAT_OK" || text === "OK" || text === "NO_REPLY") {
        this.finishStream(agentId);
        if (agentId === this.activeAgentId) {
          this.setInputDisabled(false);
        }
        return;
      }
    }
    if (payload.state === "delta" && payload.message) {
      const text = payload.message.content.filter((c) => c.type === "text").map((c) => c.text).join("").trim();
      if (text === "HEARTBEAT_OK" || text === "OK" || text === "NO_REPLY") {
        return;
      }
    }
    if (payload.state === "error") {
      this.finishStream(agentId);
      state.messages.push({
        role: "assistant",
        content: `Error: ${(_a = payload.errorMessage) != null ? _a : "Unknown error"}`,
        timestamp: Date.now()
      });
      if (agentId === this.activeAgentId) {
        this.renderMessages();
        this.setInputDisabled(false);
      }
      return;
    }
    if (payload.state === "delta" && payload.message) {
      const text = payload.message.content.filter((c) => c.type === "text").map((c) => c.text).join("");
      this.replaceStream(agentId, text);
    }
    if (payload.state === "final") {
      if (payload.message) {
        const text = payload.message.content.filter((c) => c.type === "text").map((c) => c.text).join("");
        this.replaceStream(agentId, text);
      }
      this.finishStream(agentId);
      if (agentId === this.activeAgentId) {
        this.setInputDisabled(false);
      }
    }
  }
  handleStateChange(agentId, connected) {
    var _a;
    const tab = (_a = this.tabBarEl) == null ? void 0 : _a.querySelector(`[data-agent-id="${agentId}"]`);
    const dot = tab == null ? void 0 : tab.querySelector(".oc-tab-dot");
    if (dot) {
      dot.className = `oc-tab-dot ${connected ? "connected" : "disconnected"}`;
    }
    if (agentId === this.activeAgentId) {
      this.updateStatus();
      if (!connected) {
        const state = this.getAgentState(agentId);
        if (state.isStreaming) {
          this.finishStream(agentId);
          this.setInputDisabled(false);
        }
      }
    }
  }
  // ─── Streaming ───
  replaceStream(agentId, fullText) {
    const state = this.getAgentState(agentId);
    if (!state.isStreaming) {
      state.isStreaming = true;
      state.streamBuffer = "";
      state.streamMsgEl = null;
    }
    state.streamBuffer = fullText;
    if (agentId === this.activeAgentId && this.messagesEl) {
      if (!state.streamMsgEl) {
        const agent = this.plugin.settings.agents.find((a) => a.id === agentId);
        const el = this.messagesEl.createDiv({
          cls: "oc-message oc-message-assistant oc-streaming"
        });
        el.createDiv({ cls: "oc-agent-label", text: (agent == null ? void 0 : agent.name) || "Agent" });
        state.streamMsgEl = el.createDiv({ cls: "oc-bubble" });
      }
      state.streamMsgEl.setText(state.streamBuffer);
      this.scrollToBottom();
    }
  }
  finishStream(agentId) {
    const state = this.getAgentState(agentId);
    if (!state.isStreaming)
      return;
    state.isStreaming = false;
    if (state.streamBuffer) {
      const { text, actions } = this.extractActions(state.streamBuffer);
      state.messages.push({
        role: "assistant",
        content: text,
        timestamp: Date.now()
      });
      if (actions.length > 0) {
        this.executeActions(actions);
      }
    }
    state.streamBuffer = "";
    state.streamMsgEl = null;
    if (agentId === this.activeAgentId) {
      this.renderMessages();
    }
  }
  // ─── Rendering ───
  renderMessages() {
    if (!this.messagesEl || !this.activeAgentId)
      return;
    this.messagesEl.empty();
    const state = this.getAgentState(this.activeAgentId);
    const agent = this.plugin.settings.agents.find((a) => a.id === this.activeAgentId);
    for (const msg of state.messages) {
      this.renderMessage(msg, agent);
    }
    if (state.isStreaming && state.streamBuffer) {
      const el = this.messagesEl.createDiv({
        cls: "oc-message oc-message-assistant oc-streaming"
      });
      el.createDiv({ cls: "oc-agent-label", text: (agent == null ? void 0 : agent.name) || "Agent" });
      state.streamMsgEl = el.createDiv({ cls: "oc-bubble" });
      state.streamMsgEl.setText(state.streamBuffer);
    }
    this.scrollToBottom();
  }
  renderMessage(msg, agent) {
    if (!this.messagesEl)
      return;
    const el = this.messagesEl.createDiv({
      cls: `oc-message oc-message-${msg.role}`
    });
    if (msg.role === "assistant") {
      el.createDiv({ cls: "oc-agent-label", text: (agent == null ? void 0 : agent.name) || "Agent" });
    }
    const bubble = el.createDiv({ cls: "oc-bubble" });
    bubble.setText(msg.content);
    const ts = new Date(msg.timestamp);
    const timeStr = ts.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });
    bubble.setAttribute("title", timeStr);
  }
  updateStatus() {
    if (!this.statusEl || !this.activeAgentId)
      return;
    const connected = this.plugin.gatewayManager.isConnected(this.activeAgentId);
    this.statusEl.setText(connected ? "\u25CF Connected" : "\u25CB Disconnected");
    this.statusEl.className = `oc-status-bar ${connected ? "connected" : "disconnected"}`;
  }
  showEmptyState() {
    if (this.chatAreaEl)
      this.chatAreaEl.style.display = "none";
    if (!this.emptyStateEl)
      return;
    this.emptyStateEl.style.display = "flex";
    this.emptyStateEl.empty();
    this.emptyStateEl.createDiv({ cls: "oc-empty-icon" });
    (0, import_obsidian.setIcon)(this.emptyStateEl.querySelector(".oc-empty-icon"), "message-circle");
    this.emptyStateEl.createDiv({
      cls: "oc-empty-title",
      text: "No agents configured"
    });
    const link = this.emptyStateEl.createEl("a", {
      cls: "oc-empty-link",
      text: "Open Settings to add an agent"
    });
    link.addEventListener("click", () => {
      this.app.setting.open();
      this.app.setting.openTabById("openclaw-chat");
    });
  }
  showInlineWarning(text) {
    if (!this.messagesEl)
      return;
    const state = this.getAgentState(this.activeAgentId);
    if (state.messages.length > 0)
      return;
    const warn = this.messagesEl.createDiv({ cls: "oc-token-warning" });
    const warningText = warn.createSpan({ text: "\u26A0 " + text + " " });
    const link = warningText.createEl("a", { cls: "oc-settings-link", text: "Open Settings" });
    link.addEventListener("click", () => {
      this.app.setting.open();
      this.app.setting.openTabById("openclaw-chat");
    });
  }
  // ─── Input ───
  async handleSend() {
    var _a, _b, _c;
    const text = (_b = (_a = this.inputEl) == null ? void 0 : _a.value) == null ? void 0 : _b.trim();
    if (!text || !this.activeAgentId)
      return;
    const agent = this.plugin.settings.agents.find((a) => a.id === this.activeAgentId);
    if (!agent)
      return;
    const client = this.plugin.gatewayManager.getClient(this.activeAgentId);
    if (!client.isConnected()) {
      new import_obsidian.Notice("Not connected to gateway. Check Settings.");
      return;
    }
    const token = this.plugin.tokenStore.get(this.activeAgentId);
    if (!token) {
      new import_obsidian.Notice("Gateway token not set. Open Settings to enter it.");
      return;
    }
    let messageToSend = text;
    let displayText = text;
    if ((_c = this.includeNoteCheckbox) == null ? void 0 : _c.checked) {
      const activeFile = this.app.workspace.getActiveFile();
      if (!activeFile) {
        new import_obsidian.Notice("No active note to include.");
        return;
      }
      const noteContent = await this.app.vault.read(activeFile);
      messageToSend = `[Current Note: ${activeFile.name}]
${noteContent}

---
${text}`;
      displayText = `\u{1F4CE} ${activeFile.basename}

${text}`;
    }
    const state = this.getAgentState(this.activeAgentId);
    state.messages.push({ role: "user", content: displayText, timestamp: Date.now() });
    this.renderMessages();
    if (this.inputEl)
      this.inputEl.value = "";
    this.setInputDisabled(true);
    try {
      await client.sendChat(agent.sessionKey, messageToSend);
    } catch (e) {
      this.finishStream(this.activeAgentId);
      state.messages.push({
        role: "assistant",
        content: `Failed to send: ${e.message}`,
        timestamp: Date.now()
      });
      this.renderMessages();
      this.setInputDisabled(false);
    }
  }
  setInputDisabled(disabled) {
    if (this.inputEl)
      this.inputEl.disabled = disabled;
    if (this.sendBtn)
      this.sendBtn.disabled = disabled;
  }
  // ─── Agent state ───
  getAgentState(agentId) {
    let state = this.agentStates.get(agentId);
    if (!state) {
      state = {
        messages: [],
        streamBuffer: "",
        streamMsgEl: null,
        isStreaming: false
      };
      this.agentStates.set(agentId, state);
    }
    return state;
  }
  /** Send a message programmatically as the user (used by "Ask Agent about this note") */
  async sendMessage(text) {
    if (!this.activeAgentId)
      return;
    const agent = this.plugin.settings.agents.find((a) => a.id === this.activeAgentId);
    if (!agent)
      return;
    const client = this.plugin.gatewayManager.getClient(this.activeAgentId);
    if (!client.isConnected()) {
      new import_obsidian.Notice("Not connected to gateway. Check Settings.");
      return;
    }
    const state = this.getAgentState(this.activeAgentId);
    state.messages.push({ role: "user", content: text, timestamp: Date.now() });
    this.renderMessages();
    this.setInputDisabled(true);
    try {
      await client.sendChat(agent.sessionKey, text);
    } catch (e) {
      this.finishStream(this.activeAgentId);
      state.messages.push({
        role: "assistant",
        content: `Failed to send: ${e.message}`,
        timestamp: Date.now()
      });
      this.renderMessages();
      this.setInputDisabled(false);
    }
  }
  clearActiveChat() {
    if (!this.activeAgentId)
      return;
    const state = this.getAgentState(this.activeAgentId);
    state.messages = [];
    state.streamBuffer = "";
    state.streamMsgEl = null;
    state.isStreaming = false;
    this.renderMessages();
  }
  // ─── Utils ───
  scrollToBottom() {
    if (this.messagesEl) {
      requestAnimationFrame(() => {
        if (this.messagesEl) {
          this.messagesEl.scrollTop = this.messagesEl.scrollHeight;
        }
      });
    }
  }
  // ─── Action blocks ───
  extractActions(content) {
    const regex = /```json:oc-actions\s*\n([\s\S]*?)```/g;
    let actions = [];
    const text = content.replace(regex, (_match, json) => {
      try {
        const parsed = JSON.parse(json.trim());
        if (Array.isArray(parsed)) {
          actions = actions.concat(parsed);
        }
      } catch (e) {
        return _match;
      }
      return "";
    }).trim();
    return { text, actions };
  }
  async executeActions(actions) {
    var _a, _b, _c;
    const results = [];
    for (const action of actions) {
      try {
        switch (action.action) {
          case "openFile": {
            const file = this.app.vault.getAbstractFileByPath(action.path);
            if (file instanceof import_obsidian.TFile) {
              await this.app.workspace.getLeaf(false).openFile(file);
              results.push(`Opened ${action.path}`);
            } else {
              results.push(`File not found: ${action.path}`);
            }
            break;
          }
          case "createFile": {
            const confirmed = await this.confirmAction(
              "Create File",
              `Create new note at:
${action.path}`
            );
            if (!confirmed) {
              results.push(`Skipped creating ${action.path}`);
              break;
            }
            const dir = action.path.substring(0, action.path.lastIndexOf("/"));
            if (dir) {
              await this.ensureFolder(dir);
            }
            await this.app.vault.create(action.path, (_a = action.content) != null ? _a : "");
            results.push(`Created ${action.path}`);
            break;
          }
          case "updateFile": {
            const confirmed = await this.confirmAction(
              "Overwrite File",
              `This will overwrite:
${action.path}`
            );
            if (!confirmed) {
              results.push(`Skipped updating ${action.path}`);
              break;
            }
            const file = this.app.vault.getAbstractFileByPath(action.path);
            if (file instanceof import_obsidian.TFile) {
              await this.app.vault.modify(file, (_b = action.content) != null ? _b : "");
              results.push(`Updated ${action.path}`);
            } else {
              results.push(`File not found: ${action.path}`);
            }
            break;
          }
          case "appendToFile": {
            const confirmed = await this.confirmAction(
              "Append to File",
              `Append content to:
${action.path}`
            );
            if (!confirmed) {
              results.push(`Skipped appending to ${action.path}`);
              break;
            }
            const file = this.app.vault.getAbstractFileByPath(action.path);
            if (file instanceof import_obsidian.TFile) {
              await this.app.vault.append(file, (_c = action.content) != null ? _c : "");
              results.push(`Appended to ${action.path}`);
            } else {
              results.push(`File not found: ${action.path}`);
            }
            break;
          }
          case "deleteFile": {
            const confirmed = await this.confirmAction(
              "Delete File",
              `Are you sure you want to delete:
${action.path}

This cannot be undone.`
            );
            if (!confirmed) {
              results.push(`Skipped deleting ${action.path}`);
              break;
            }
            const file = this.app.vault.getAbstractFileByPath(action.path);
            if (file instanceof import_obsidian.TFile) {
              await this.app.vault.delete(file);
              results.push(`Deleted ${action.path}`);
            } else {
              results.push(`File not found: ${action.path}`);
            }
            break;
          }
          case "renameFile": {
            const confirmed = await this.confirmAction(
              "Rename File",
              `Rename:
${action.path}
to:
${action.newPath}`
            );
            if (!confirmed) {
              results.push(`Skipped renaming ${action.path}`);
              break;
            }
            const file = this.app.vault.getAbstractFileByPath(action.path);
            if (file instanceof import_obsidian.TFile && action.newPath) {
              await this.app.vault.rename(file, action.newPath);
              results.push(`Renamed ${action.path} \u2192 ${action.newPath}`);
            } else {
              results.push(`File not found: ${action.path}`);
            }
            break;
          }
          default:
            results.push(`Unknown action: ${action.action}`);
        }
      } catch (e) {
        results.push(`Error: ${e.message}`);
      }
    }
    if (results.length > 0) {
      new import_obsidian.Notice(results.join("\n"), 8e3);
    }
  }
  confirmAction(title, message) {
    return new Promise((resolve) => {
      const modal = new ConfirmModal(this.app, title, message, resolve);
      modal.open();
    });
  }
  async ensureFolder(path) {
    const existing = this.app.vault.getAbstractFileByPath(path);
    if (!existing) {
      await this.app.vault.createFolder(path);
    }
  }
  async onClose() {
    this.unbindAllAgentListeners();
  }
};
var ConfirmModal = class extends import_obsidian.Modal {
  constructor(app, title, message, resolve) {
    super(app);
    this.title = title;
    this.message = message;
    this.resolve = resolve;
  }
  onOpen() {
    this.containerEl.addClass("oc-confirm-modal");
    const { contentEl } = this;
    contentEl.createEl("h3", { text: this.title });
    for (const line of this.message.split("\n")) {
      contentEl.createEl("p", { text: line });
    }
    const btnContainer = contentEl.createDiv({ cls: "modal-button-container" });
    const cancelBtn = btnContainer.createEl("button", { text: "Cancel" });
    cancelBtn.addEventListener("click", () => {
      this.resolve(false);
      this.close();
    });
    const confirmBtn = btnContainer.createEl("button", { cls: "mod-cta", text: "Confirm" });
    confirmBtn.addEventListener("click", () => {
      this.resolve(true);
      this.close();
    });
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/settings.ts
var import_obsidian2 = require("obsidian");
var OcChatSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.addClass("oc-settings");
    containerEl.createEl("h2", { text: "OpenClaw Chat \u2014 Agents" });
    containerEl.createEl("p", {
      text: "Configure one or more AI agents. Tokens are stored in memory only and must be re-entered after restarting Obsidian.",
      cls: "setting-item-description"
    });
    const agentList = containerEl.createDiv({ cls: "oc-agent-list" });
    for (const agent of this.plugin.settings.agents) {
      this.renderAgentCard(agentList, agent);
    }
    containerEl.createEl("h2", { text: "Integrations" });
    new import_obsidian2.Setting(containerEl).setName("Note Sync").setDesc("Coming Soon \u2014 two-way note synchronisation with agents").addToggle(
      (toggle) => toggle.setValue(false).setDisabled(true)
    );
    new import_obsidian2.Setting(containerEl).addButton(
      (btn) => btn.setButtonText("+ Add Agent").setCta().onClick(async () => {
        const id = crypto.randomUUID();
        const agent = {
          id,
          name: "",
          gatewayUrl: "",
          sessionKey: "obsidian:main",
          enabled: true
        };
        this.plugin.settings.agents.push(agent);
        await this.plugin.saveSettings();
        this.display();
      })
    );
  }
  renderAgentCard(container, agent) {
    const card = container.createDiv({ cls: "oc-agent-card" });
    const connected = this.plugin.gatewayManager.isConnected(agent.id);
    const header = card.createDiv({ cls: "oc-agent-card-header" });
    header.createSpan({
      cls: `oc-status-dot ${connected ? "connected" : "disconnected"}`
    });
    const titleEl = header.createSpan({
      cls: "oc-agent-card-title",
      text: agent.name || "Unnamed Agent"
    });
    const urlHint = header.createSpan({
      cls: "oc-agent-card-url",
      text: this.safeHostname(agent.gatewayUrl)
    });
    const expandBtn = header.createEl("button", {
      cls: "oc-agent-expand-btn clickable-icon",
      attr: { "aria-label": "Expand" }
    });
    (0, import_obsidian2.setIcon)(expandBtn, "chevron-down");
    const body = card.createDiv({ cls: "oc-agent-card-body collapsed" });
    const toggleExpand = () => {
      body.toggleClass("collapsed", !body.hasClass("collapsed"));
      expandBtn.toggleClass("expanded", !body.hasClass("collapsed"));
    };
    expandBtn.addEventListener("click", toggleExpand);
    header.addEventListener("click", (e) => {
      if (e.target === expandBtn || expandBtn.contains(e.target))
        return;
      toggleExpand();
    });
    new import_obsidian2.Setting(body).setName("Agent Name").setDesc("Display name shown in chat tabs").addText(
      (text) => text.setPlaceholder("e.g. Agent").setValue(agent.name).onChange(async (value) => {
        agent.name = value;
        titleEl.setText(value || "Unnamed Agent");
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(body).setName("Gateway URL").setDesc("Your OpenClaw gateway URL").addText(
      (text) => text.setPlaceholder("https://your-gateway.ts.net").setValue(agent.gatewayUrl).onChange(async (value) => {
        agent.gatewayUrl = value.replace(/\/+$/, "");
        urlHint.setText(this.safeHostname(value));
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(body).setName("Gateway Token").setDesc("Stored in memory only \u2014 re-enter after restart").addText((text) => {
      var _a;
      text.inputEl.type = "password";
      text.inputEl.placeholder = "Paste your gateway token";
      text.inputEl.value = (_a = this.plugin.tokenStore.get(agent.id)) != null ? _a : "";
      text.inputEl.addEventListener("change", (e) => {
        const val = e.target.value.trim();
        if (val) {
          this.plugin.tokenStore.set(agent.id, val);
        } else {
          this.plugin.tokenStore.delete(agent.id);
        }
      });
    });
    new import_obsidian2.Setting(body).setName("Session Key").setDesc("Advanced \u2014 leave as default unless told otherwise").addText(
      (text) => text.setPlaceholder("obsidian:main").setValue(agent.sessionKey).onChange(async (value) => {
        agent.sessionKey = value || "obsidian:main";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(body).setName("Enabled").setDesc("Show this agent in chat tabs").addToggle(
      (toggle) => toggle.setValue(agent.enabled).onChange(async (value) => {
        agent.enabled = value;
        await this.plugin.saveSettings();
        if (!value) {
          this.plugin.gatewayManager.disconnectAgent(agent.id);
        }
        this.plugin.refreshChatView();
      })
    );
    const actions = body.createDiv({ cls: "oc-agent-actions" });
    const testBtn = actions.createEl("button", {
      cls: "mod-cta",
      text: "Test Connection"
    });
    testBtn.addEventListener("click", async () => {
      const url = agent.gatewayUrl;
      const token = this.plugin.tokenStore.get(agent.id);
      if (!url) {
        new import_obsidian2.Notice("Enter a Gateway URL first.");
        return;
      }
      if (!token) {
        new import_obsidian2.Notice("Enter a Gateway Token first.");
        return;
      }
      testBtn.setText("Testing\u2026");
      testBtn.disabled = true;
      try {
        const client = this.plugin.gatewayManager.getClient(agent.id);
        const result = await client.testConnection(url, token);
        new import_obsidian2.Notice(`${agent.name || "Agent"}: ${result}`);
        this.plugin.connectAgent(agent.id);
        this.display();
      } catch (e) {
        new import_obsidian2.Notice(`${agent.name || "Agent"}: ${e.message}`);
      } finally {
        testBtn.setText("Test Connection");
        testBtn.disabled = false;
      }
    });
    const deleteBtn = actions.createEl("button", {
      cls: "mod-warning",
      text: "Delete Agent"
    });
    deleteBtn.addEventListener("click", async () => {
      if (!confirm(`Delete agent "${agent.name || "Unnamed"}"? This cannot be undone.`))
        return;
      this.plugin.gatewayManager.removeAgent(agent.id);
      this.plugin.tokenStore.delete(agent.id);
      this.plugin.settings.agents = this.plugin.settings.agents.filter(
        (a) => a.id !== agent.id
      );
      await this.plugin.saveSettings();
      this.plugin.refreshChatView();
      this.display();
    });
  }
  safeHostname(url) {
    if (!url)
      return "No URL set";
    try {
      return new URL(url).hostname;
    } catch (e) {
      return url;
    }
  }
};

// src/types.ts
var DEFAULT_SETTINGS = {
  agents: []
};

// main.ts
var OcChatPlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.settings = { ...DEFAULT_SETTINGS };
    this.gatewayManager = new GatewayManager();
    // Tokens live in memory only — never persisted to disk
    this.tokenStore = /* @__PURE__ */ new Map();
  }
  async onload() {
    await this.loadSettings();
    this.registerView(CHAT_VIEW_TYPE, (leaf) => new ChatView(leaf, this));
    this.addRibbonIcon("message-circle", "Open OpenClaw Chat", () => {
      this.activateChatView();
    });
    this.addCommand({
      id: "open-oc-chat",
      name: "Open Chat",
      callback: () => this.activateChatView()
    });
    this.registerAgentCommands();
    this.addSettingTab(new OcChatSettingTab(this.app, this));
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (!(file instanceof import_obsidian3.TFile) || file.extension !== "md")
          return;
        menu.addItem((item) => {
          item.setTitle("Ask Agent about this note").setIcon("message-circle").onClick(async () => {
            await this.askAgentAboutNote(file);
          });
        });
      })
    );
    setTimeout(() => this.autoConnectAgents(), 1e3);
    console.log("OpenClaw Chat v2 loaded");
  }
  async onunload() {
    this.gatewayManager.disconnectAll();
    console.log("OpenClaw Chat v2 unloaded");
  }
  async loadSettings() {
    const data = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, data);
    if (!Array.isArray(this.settings.agents)) {
      this.settings.agents = [];
    }
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  connectAgent(agentId) {
    const agent = this.settings.agents.find((a) => a.id === agentId);
    if (!agent)
      return;
    const token = this.tokenStore.get(agentId);
    if (!agent.gatewayUrl || !token)
      return;
    this.gatewayManager.connectAgent(agentId, agent.gatewayUrl, token);
  }
  autoConnectAgents() {
    for (const agent of this.settings.agents) {
      if (agent.enabled && agent.gatewayUrl && this.tokenStore.has(agent.id)) {
        this.connectAgent(agent.id);
      }
    }
  }
  registerAgentCommands() {
    for (const agent of this.settings.agents) {
      if (!agent.enabled || !agent.name)
        continue;
      this.addCommand({
        id: `switch-agent-${agent.id}`,
        name: `Switch to Agent: ${agent.name}`,
        callback: async () => {
          await this.activateChatView();
          const view = this.getChatView();
          if (view)
            view.switchToAgent(agent.id);
        }
      });
    }
  }
  refreshChatView() {
    const view = this.getChatView();
    if (view)
      view.refresh();
  }
  getChatView() {
    const leaves = this.app.workspace.getLeavesOfType(CHAT_VIEW_TYPE);
    if (leaves.length > 0) {
      return leaves[0].view;
    }
    return null;
  }
  async activateChatView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(CHAT_VIEW_TYPE);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getRightLeaf(false);
      if (leaf) {
        await leaf.setViewState({ type: CHAT_VIEW_TYPE, active: true });
      }
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
    }
  }
  async askAgentAboutNote(file) {
    const content = await this.app.vault.cachedRead(file);
    if (!this.getChatView()) {
      await this.activateChatView();
    }
    const chatView = this.getChatView();
    if (!chatView) {
      new import_obsidian3.Notice("Could not open chat panel.");
      return;
    }
    const message = `I'd like to discuss this note:

**${file.basename}**

${content}`;
    await chatView.sendMessage(message);
    const leaves = this.app.workspace.getLeavesOfType(CHAT_VIEW_TYPE);
    if (leaves.length > 0) {
      this.app.workspace.revealLeaf(leaves[0]);
    }
  }
};
